server:
  port: 8001
  shutdown: graceful

spring:
  lifecycle:
    # 停机等待的最长时间（例如 30 秒）
    timeout-per-shutdown-phase: 30s
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 5000ms
      connect-timeout: 10000ms
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'

  mvc:
    view:
      prefix: /templates/
      suffix: .html
short-link:
  domain:
    default: localhost:8001
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
  stats:
    locale:
      amap-key: c8a494b480ecb0b73c26a41881a93b68
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

